### ISSUE TITLE
NPE after closing Logistic station window

### ISSUE THREAD

**Issue by mitasov-ra** [LittleSaya/DSPTransportStat#1]
![image](https://user-images.githubusercontent.com/29340679/169652600-30808e9f-75f3-434e-bcea-65f47d1625c5.png)

### Impact

 It's impossible to manually open Logistic Station window after this error occurs

### Steps to reproduce
1. Manually open logistic station window
2. Manually close window

### Installed mods

- BepInEx by xiaoye97
- RailgunsRetargeting by brokenmass
- SplitterOverBelt by hetima
- DSP_Smooth_Splitter by GreyHak
- DSP_Belt_Reverse_Direction by GreyHak
- NebulaMultiplayerModApi by nebula
- GalacticScale by Galactic_Scale
- VanillaPlusPlusGenerator by NHunter
- Upgrade_Amount by testpushpleaseignore
- EnableAchievements by Acceyuriko
- DSPModSave by CommonAPI
- LDBTool by xiaoye97
- CommonAPI by CommonAPI
- AssemblerUI by Shad0wlife
- CruiseAssist by tanu
- AutoPilot by tanu
- DSP_Drone_Clearing by GreyHak
- DequeCraft by ardnaxelarak
- Planet_Vein_Utilization by testpushpleaseignore
- DSPRecipeFinder by appuns
- CloseError by crecheng
- DistributeSpaceWarpers by Fireball14
- MoreMegaStructure by jinxOAO
- SlimPiler by Raptor
- OffGridConstruction by Raptor
- DSPTransportStat by IndexOutOfRange
- SphereEditorTools by starfi5h

### r2modman profile
`D9PPXpmoR0`

**Comment by LittleSaya** [comment]
I just uploaded version 0.0.9, this problem should got fixed in that version.
